### ISSUE TITLE
Login Issues

### ISSUE THREAD

**Issue by pokiller** [voyageur/dagr#18]
I am using this command:
dagr.py -u username -p password -g [artist]
I used the command before and it was fine, but now it seems to have some login issues.

> dagr.py v0.63 - deviantArt gallery ripper
Attempting to log in to deviantArt...
Traceback (most recent call last):
  File "C:\Python27\Scripts\dagr.py", line 628, in <module>
    main()
  File "C:\Python27\Scripts\dagr.py", line 576, in main
    ripper.start()
  File "C:\Python27\Scripts\dagr.py", line 93, in start
    self.login()
  File "C:\Python27\Scripts\dagr.py", line 134, in login
    form['username'] = self.username
  File "C:\Python27\lib\site-packages\robobrowser-0.5.3-py2.7.egg\robobrowser\forms\form.py", line 216, in __setitem__
    self.fields[key].value = value
  File "C:\Python27\lib\site-packages\werkzeug-0.12.2-py2.7.egg\werkzeug\datastructures.py", line 781, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

**Comment by voyageur** [comment]
Indeed, the login form now has reCAPTCHA enabled...

I guess I will drop all the login/password stuff, as we can access our own favourites without being logged in (and mature content works for now with #11)

**Comment by voyageur** [comment]
OK between cff44a6 and f445f33 I think all "easy" fixes are in

**Comment by pokiller** [comment]
It works! Thank you so much XD
