### ISSUE TITLE
0.71 does not work with python2

### ISSUE THREAD

**Issue by voyageur** [voyageur/dagr#35]
As reported by @rickjthree in #33 
`$ dagr.py -g phil-chodagr.py v0.71 - deviantArt gallery ripperCurrent deviant: phil-choRipping phil-cho's gallery...Traceback (most recent call last):  File "/usr/bin/dagr.py", line 4, in <module>    __import__('pkg_resources').run_script('dagr==0.71', 'dagr.py')  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 738, in run_script    self.require(requires)[0].run_script(script_name, ns)  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1506, in run_script    exec(script_code, namespace, namespace)  File "/usr/lib/python2.7/site-packages/dagr-0.71-py2.7.egg/EGG-INFO/scripts/dagr.py", line 571, in <module>
  File "/usr/lib/python2.7/site-packages/dagr-0.71-py2.7.egg/EGG-INFO/scripts/dagr.py", line 554, in main
  File "/usr/lib/python2.7/site-packages/dagr-0.71-py2.7.egg/EGG-INFO/scripts/dagr.py", line 334, in deviant_get
  File "/usr/lib/python2.7/site-packages/dagr-0.71-py2.7.egg/EGG-INFO/scripts/dagr.py", line 236, in get_pages
  File "/usr/lib/python2.7/site-packages/dagr-0.71-py2.7.egg/EGG-INFO/scripts/dagr.py", line 143, in get
  File "/usr/lib/python2.7/site-packages/mechanicalsoup/stateful_browser.py", line 346, in download_link    link = self._find_link_internal(link, args, kwargs)  File "/usr/lib/python2.7/site-packages/mechanicalsoup/stateful_browser.py", line 299, in _find_link_internal    return self.find_link(*args, **kwargs)  File "/usr/lib/python2.7/site-packages/mechanicalsoup/stateful_browser.py", line 271, in find_link    links = self.links(*args, **kwargs)  File "/usr/lib/python2.7/site-packages/mechanicalsoup/stateful_browser.py", line 253, in links    all_links = self.get_current_page().find_all(AttributeError: 'NoneType' object has no attribute 'find_all'`

Also tested locally, at least checking types on str does not work with python2, and utime calls later on do not work on py2:
`TypeError: utime() takes no keyword arguments`

**Comment by voyageur** [comment]
Pushed a quick fix to master, will wait for some feedback (or personal tests) before tagging a new release :)

**Comment by Joeppie** [comment]
I just cloned, install and ran dagr, it seems to run fine with Python 2.7.12.

**Comment by voyageur** [comment]
Thanks for the test, I suspect the issue you ran into was some website hickup on DA side. If it happens again we can track it in another issue, in the meantime I will make a 0.71.1 release for those not using git directly.

**Comment by Ailothaen** [comment]
I'm getting a bit of the same error ; however, I'm running Python 3 (3.7.1 to be exact) : 

```
python dagr.py Ailothaen -g
dagr.py v0.71 - deviantArt gallery ripper
Current deviant: Ailothaen
Ripping Ailothaen's gallery...
Ailothaen's gallery page 1 crawled...
Total deviations in Ailothaen's gallery found: 2
Total deviations to download: 2
Traceback (most recent call last):
  File "D:\PATH\dagr.py", line 571, in <module>
    main()
  File "D:\PATH\dagr.py", line 554, in main
    ripper.deviant_get("gallery")
  File "D:\PATH\dagr.py", line 341, in deviant_get
    self.get_images(mode, mode_arg, pages)
  File "D:\PATH\dagr.py", line 302, in get_images
    self.get(filelink, base_dir + "/" + filename)
  File "D:\PATH\dagr.py", line 159, in get
    get_resp.headers.get("content-type")))
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by Joeppie** [comment]
Hiya, no I do not believe the issue is specific to DeviantArt having a hiccup, it consistently occured when there were more than 200+ deviations to download, but ceased to occur and did not occur with a 600+ collection when I was using the one that was specifically in the build/scripts folder.

What the difference between these two is, I would not be able to tell you, however, did not look into it.
